# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Bento iOS' do
  pod 'Mixpanel'
end

target 'Bento Android' do

end

target 'Bento Mac' do

end

